version: '3'

services:

  submit:
    build:
      context: ..
      dockerfile: compose/submit/Dockerfile
    environment:
      - RIDERS_USERNAME=${RIDERS_USERNAME}
      - RIDERS_PASSWORD=${RIDERS_PASSWORD}
      - DESCRIPTION=${DESCRIPTION}
      - RIDERS_AUTH_TOKEN=${RIDERS_AUTH_TOKEN}
      - TOKEN_FILE=${TOKEN_FILE}
    volumes:
      - ..:/project